### ISSUE TITLE
Fox's commit 9e381bc causes major breakage

### ISSUE THREAD

**Issue by martywd** [Strayer/tt-rss-favicon-unread-counter#1]
After commit (9e381bc) tt-rss browser client goes to blank page.

9e381bc commit link:
https://tt-rss.org/fox/tt-rss/commit/9e381bc2021dc427f62c463dac9cf7a82a66616f

After doing a 'git checkout 7611f0c' (previous commit), then able to connect as expected.  Logged into client admin account and checking log (Preferences|System) shows errors like this:

`E_ERROR (1)     plugins.local/favicon_unread_counter/init.php:0 Class Favicon_Unread_Counter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods `(Plugin::init)`

`E_ERROR` (1)     plugins.local/favicon_unread_counter/init.php:0 Class Favicon_Unread_Counter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods `(Plugin::init`

Still at commit 7611f0c logged into my 'user' profile, disabled 'favicon-unread-counter' plugin, save.

Now back into commit '9e381bc' all is well, except for...   After save, in 'Preferences|Plugins' no plugins were listed.  Reloading page did not help.  Ended up moving the 'favicon_unread_counter' directory out of ../plugins.local directory and outside of my tt-rss install.  Then on reload of 'Preference|Plugins' list of available plugins was now viewable.
.

**Comment by strayer** [comment]
Hey @martywd, thanks for reporting. Will try to fix this today. Not sure what caused the issue with the missing plugins though, maybe something changed in the configuration format in that commit? Edit: Or rather something changed in-between. Regardless… will check that the plugin works with the newest TT-RSS version!

**Comment by strayer** [comment]
Please check [version 1.2.0](https://github.com/Strayer/tt-rss-favicon-unread-counter/releases/tag/v1.2.0), should be fixed!

**Comment by martywd** [comment]
> @Strayer  -- Please check version 1.2.0, should be fixed!

1.2.0 installed.  All is functioning as expected and no log errors.

Thank you!
.
